version: '2.2'

networks:
  internal:
    driver: bridge

volumes:
  nexus-data:

services:
  nexus3:
    image: 'sonatype/nexus3'
    healthcheck:
      test: ['CMD', 'curl', '-fIu', 'admin:admin123', 'http://localhost:8081/service/metrics/ping']
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - 8081:8081
    expose:
      - 8081/tcp
    networks:
      - internal
    volumes:
      - 'nexus-data:/nexus-data'
