version: '2.2'

networks:
  internal:
    driver: bridge
  consul-network:
    external:
      name: docker-compose-ha-consul-vault-ui_internal

volumes:
  nexus-data:

services:
  nexus3:
    image: 'sonatype/nexus3'
    init: true
    healthcheck:
      test:
        - CMD
        - /bin/bash
        - -ec
        - |
          curl -fI http://localhost:8081/nexus/service/rest/v1/status
      interval: 45s
      timeout: 30s
      retries: 6
    #ports:
    #  - 8081:8081
    #restart: on-failure
    expose:
      - 8081/tcp
      - 8082/tcp
      - 8083/tcp
    networks:
      - internal
      - consul-network
    volumes:
      - 'nexus-data:/nexus-data'
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/consul:/usr/local/bin/consul:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/jq:/usr/local/bin/jq:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/scripts/consul-agent.sh:/bin/consul-agent.sh:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/scripts/vault-functions.sh:/usr/local/share/vault-functions.sh:ro
      - ${HOME}/git/github/docker-compose-ha-consul-vault-ui/vault:/usr/local/bin/vault:ro
    dns:
      - 172.16.238.2
      - 172.16.238.3
    user: root
    command:
      - /bin/sh
      - -c
      - |
        # this will start Nexus with a consul agent
        set -ex
        dnf makecache
        dnf install -y zip
        IP="$$(awk '/32 host/ && f ~ /172.16.238/ { print f; exit }; {f=$$2}' /proc/net/fib_trie)"
        consul-agent.sh --consul-host consul.service.consul --advertise "$$IP" --service '{"service": {"name": "nexus", "tags": ["portal"], "port": 8081, "meta": {"title": "Nexus 3", "description": "Nexus artifact repository for hosting software."}}}'
        env | awk '/NEXUS|INSTALL4J|SONATYPE/ { print "export \""$$0"\"" }' > /tmp/environ.sh
        echo 'export NEXUS_CONTEXT=nexus' >> /tmp/environ.sh
        exec su -s /bin/sh -c "set -ex; source /tmp/environ.sh; exec $${SONATYPE_DIR}"/start-nexus-repository-manager.sh - nexus
